### ISSUE TITLE
инфа

### ISSUE THREAD

**Issue by Fire285** [pyadrus/TelegramMaster_Report_by.PyAdminRUS#1]
Проект хороший, но  есть препятствия.
1) Сейчас при массовых репортах достаточно  быстро умирают учетки с которых идет репорт, ( особенно если они на одном айпи )
нужны хорошие прокси желательно индивидуальные мобильные или мтпрокси.
2) Нужны аккаунты старше 6 месяцев и при этом прогретые чтобы в них и контакты были и общались до этого между собой хотябы и не только.

**Comment by pyadrus** [comment]
Все действия с программой будут осуществляться пользователями. Я же занимаюсь только созданием инструмента с открытым исходным кодом и стремлюсь к совершенствованию своих навыков программирования, используя новые подходы, которые ранее не применял. Как именно пользователи будут использовать этот инструмент — решать им самим.

Важно, чтобы каждый пользователь понимал: использование чужих аккаунтов, которые ему не принадлежат, является уголовным преступлением во многих странах. Возможно, ваша информация будет полезна кому-то.

**Comment by Fire285** [comment]
так я про другое бро.
Свои даже акки если и их много с одного айпи темболее при репортах вероятность высока улетит что вся сетка в бан.
над каждому ааку по прокси крепить или на 2-3 хотяб отдельный.

**Comment by pyadrus** [comment]
Приму к сведенью вашу информацию.
